### ISSUE TITLE
_hideRightIcon, _hideLeftIcon not set if dot is clicked

### ISSUE THREAD

**Issue by mlisook** [a1626/image-carousel#3]
Very nice element.

The `_hideRightIcon` and `_hideLeftIcon` are not set if the user navigates by tapping one of the dots.  That can leave the right or left buttons in the incorrect visibility state.

**Comment by a1626** [comment]
@mlisook thanks for reporting the bug. I'll fix it ASAP

**Comment by a1626** [comment]
leaving the issue opened till i publish a new version

**Comment by a1626** [comment]
This issue is now fixed in `v1.1.0`. 

Thanks a lot for reporting the issue. I've created and integrated test cases with `travis` so as to avoid such cases in future commits.
